### ISSUE TITLE
Removal of Search Bar

### ISSUE THREAD

**Issue by AndyC-CMTC** [michalsukupcak/G-Suite-New-Tab#1]
Hi

Such a shame you removed this feature.  The tool no longer forms the great launch pad it was for us.  Our users use GSuite and obviously search using Google. I am pretty certain our users will ditch the extension now. Whenever they want to search the Web they now have to type in a URL just to get to a search engine.

**Comment by michalsukupcak** [comment]
Hello Andy,

Thank you for reaching out! My reasoning for removal is that it is merely a duplicate functionality for what the address bar / omnibox of Chrome already offers: You can initialize search just by typing directly into the address bar of Chrome (you don't have to open google.com for that).

However, if you feel the search bar is useful, I can add it back right away. :)

**Comment by michalsukupcak** [comment]
Update 2.1.0 of the extension (will go live in about an hour) addresses the search bar issue. If you have any other suggestions, please let me know.

**Comment by AndyC-CMTC** [comment]
Many thanks

Andy

*Andrew Close*
Managing Director

andy.close@counterpoint.co.uk
www.cmtc.co.uk

*Counterpoint MTC Ltd*
2 Timberlaine Trading Estate
Decoy Road
Worthing
West Sussex
BN14 8ND

tel: +44 1903 538844
fax: +44 1903 536080

Registration number: 03977697
Registered office: Amelia House, Crescent Road, Worthing, BN11 1QR
Place of registration: England
