### ISSUE TITLE
Dashboard Customization

### ISSUE THREAD

**Issue by danmcatee** [michalsukupcak/G-Suite-New-Tab#3]
First of all thank you for that awesome extension.

Is there a way to customize what the dashboard is showing, or to disable it completely?

**Comment by michalsukupcak** [comment]
Hi, Dan,

Thanks for the feature idea. I've been considering adding more customization options, including ability to hide "Dashboard" and "Bookmarks", however, currently I have very little free time to develop the extension.

Although I'm considering a complete rewrite now that Polymer 3.0 has been released, so I might as well add this feature. I can't give you an ETA however, it all depends on how much time I'll have outside of work over the coming months.

**Comment by michalsukupcak** [comment]
Hi, Dan,

I've just published version 2.4.0 of the extension which adds the ability to toggle visibility of both Dashboard and Bookmarks cards.

Update should be live now, so either visit chrome://extensions and click the update button to update manually (you have to enable Developer mode to see the button first) or wait for Chrome to check for extension updates automatically for you within the next few hours/days.
